let ome = {
  token: {
    id: "tok_1JkUuPHuRdGEFSeWJK5xvo0F",
    object: "token",
    card: {
      id: "card_1JkUuPHuRdGEFSeWo0jklQ2c",
      object: "card",
      address_city: "Jakarta Timur",
      address_country: "Indonesia",
      address_line1: "kentangj",
      address_line1_check: "unchecked",
      address_line2: null,
      address_state: null,
      address_zip: "17610",
      address_zip_check: "unchecked",
      brand: "Visa",
      country: "US",
      cvc_check: "unchecked",
      dynamic_last4: null,
      exp_month: 10,
      exp_year: 2021,
      funding: "credit",
      last4: "4242",
      name: "Kentang",
      tokenization_method: null,
    },
    client_ip: "103.217.219.154",
    created: 1634221669,
    email: "kentang8250@gmail.com",
    livemode: false,
    type: "card",
    used: false,
  },
  cartItems: [
    {
      name: "Samsung Galaxy M51 (Electric Blue, 6GB RAM, 128GB Storage)",
      quantity: 1,
      price: 300,
    },
  ],
  currentUser: {
    id: 1,
    name: "kentang8250",
    email: "kentang8250@gmail.com",
    is_staff: true,
    is_active: true,
    jwtToken:
      "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZW50YW5nODI1MEBnbWFpbC5jb20iLCJleHAiOjE2MzQyMjMzODJ9.zrmkspguwa0XEVaUucvt-iCUfxKjJnRVfgfyhKF1OFs",
  },
  subtotal: 300,
};
